### ISSUE TITLE
default styling for dl.field-list is not great for narrow display

### ISSUE THREAD

**Issue by dlech** [pybricks/support#832]
The styling uses a grid layout which causes quite a bit of wasted space as seen in the screenshot.

![image](https://user-images.githubusercontent.com/963645/206032628-bcae44df-508b-431a-9d9f-db08cb04bd4e.png)

Changing it to the following looks much better:

```css
html.writer-html5 .rst-content dl.citation,
html.writer-html5 .rst-content dl.field-list,
html.writer-html5 .rst-content dl.footnote {
    display: flex;
    flex-direction: column;
    grid-template-columns: unset;
}
```

![image](https://user-images.githubusercontent.com/963645/206033146-31833603-6aa8-4773-9175-e0c74b4e01ec.png)
